export const ADMIN_ROUTER_PATH = {
  DASH_BOARD: '/ad-dash-board',
  PRODUCT_CATEGORY: '/ad-product-category',
  ENTERPRISE: '/ad-enterprise',
  AD_CUSTOMER: '/ad-customer',
  REQUEST: '/ad-request',
  BANNER: '/ad-banner',
  FLASH_SALE: '/ad-flash-sale',
  FLASH_SALE_DETAIL: '/ad-flash-sale-detail',
  FLASH_SALE_ADD_UPDATE: '/ad-flash-sale/add-update',
  ACCOUNTS: '/ad-accounts',
  SUPPLIER_LIST: '/ad-supplier-list',
  SUPPLIER_REQ: '/ad-supplier-req',
  SUPPLIER_ADD_UPDATE: '/ad-supplier/add-update',
  SUPPLIER_DETAIL: '/ad-supplier/detail',
  POST_LIST: '/ad-post',
  POST_CONTACT: '/ad-post-contact',
  RANK: '/ad-rank',
  REQ_WITHDRAW: '/req-withdraw',
  COUPON: '/ad-coupon',
  NOTIFICATION: '/notification',
  AD_ORDER: '/ad-order',
  ORDER_DETAIL: '/ad-order-detail',
  CHAT_SUPPORT: '/ad-chat-support'
}
export const CUSTOMER_ROUTER_PATH = {
  DASH_BOARD: '/dash-board',
  PRODUCT_LIST: '/product-list',
  ORDER_LIST: '/order-list',
  AGENT: '/agent-list',
  CUSTOMER: '/customer',
  CUSTOMER_LIST: '/customer-list',
  REPORTS: '/reports',
  ACCOUNTS: '/accounts',
  WITHDRAW: '/withdraw',
  CONFIG: '/config',
  PRODUCT_UPDATE: '/update-to-product',
  PRODUCT_CREATE: '/create-to-product',
  ADD_EDIT_PRODUCT: '/add-edit-product',
  PRODUCT_DETAIL: '/product-detail',
  ORDER_DETAIL: '/order-detail',
  FLASH_SALE: '/flash-sale',
  FLASH_SALE_CONFIG_PRODUCT: '/flash-sale/config-product',
  CHAT: '/chat',
  INFO: '/info'
}

export const SESSION_ID = 'session_id'
